# Generated by Django 2.0.2 on 2018-10-12 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0003_auto_20180414_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resto', to='one_to_one.Place'),
        ),
    ]
