# Generated by Django 2.0.2 on 2018-10-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '앨범'},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name': '뮤지션'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.AddField(
            model_name='musician',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Album'),
            preserve_default=False,
        ),
    ]
