# Generated by Django 2.0.2 on 2018-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='my lovely name'),
        ),
    ]
