# Generated by Django 2.0.2 on 2018-02-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkey', '0005_auto_20180214_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foreignkey.Manufacturer', verbose_name='제조사'),
            preserve_default=False,
        ),
    ]
