# Generated by Django 2.0.2 on 2018-02-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0003_auto_20180216_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='n_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='n_pingbacks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
