# Generated by Django 2.0.2 on 2018-02-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nearby_places',
            field=models.ManyToManyField(related_query_name='near_restaurant', to='multi_table.Place'),
        ),
    ]
