# Generated by Django 2.0.2 on 2018-02-19 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0002_auto_20180208_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childa',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_base_classes.Other'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_base_classes.Other'),
        ),
    ]
