# Generated by Django 2.0.2 on 2018-10-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0004_auto_20180219_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childa',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childa_set', to='abstract_base_classes.Other'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childb_set', to='abstract_base_classes.Other'),
        ),
    ]
