# Generated by Django 2.0.2 on 2018-10-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_classes', '0005_auto_20180311_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childa',
            name='other',
        ),
        migrations.RemoveField(
            model_name='childb',
            name='other',
        ),
    ]
