# Generated by Django 2.0.2 on 2018-02-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20180209_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
