# Generated by Django 2.0.2 on 2018-02-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0004_auto_20180210_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rel.Person'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rel.Person'),
        ),
    ]
