# Generated by Django 2.0.2 on 2018-02-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0005_auto_20180210_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='person',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
