# Generated by Django 2.0.2 on 2018-02-11 06:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('custom_manager', '0002_childc_childd'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='childc',
            managers=[
                ('extra_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
