# Generated by Django 2.0.2 on 2018-02-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0009_auto_20180206_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name_plural': 'Self - FacebookUser'},
        ),
        migrations.AlterModelOptions(
            name='instagramuser',
            options={'verbose_name_plural': 'Symmetrical - InstagramUser'},
        ),
    ]
