# Generated by Django 2.0.2 on 2018-10-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(through='many_to_many.PostLike', to='many_to_many.User'),
        ),
    ]
