# Generated by Django 2.0.2 on 2018-02-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0002_restaurant_nearby_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='nearby_places',
        ),
    ]
