# Generated by Django 2.0.2 on 2018-10-11 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0003_remove_restaurant_nearby_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr123', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_table.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='multi_table.Place')),
            ],
            bases=('multi_table.place',),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='nearby_places',
            field=models.ManyToManyField(related_name='near_restaurant', related_query_name='near_restaurant', to='multi_table.Place'),
        ),
    ]
