# Generated by Django 2.0.2 on 2018-02-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0003_remove_restaurant_nearby_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multi_table.Place')),
                ('customers', models.ManyToManyField(related_name='provider', to='multi_table.Place')),
            ],
            bases=('multi_table.place',),
        ),
    ]
