# Generated by Django 2.0.2 on 2018-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0004_auto_20181011_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='customers',
            field=models.ManyToManyField(related_query_name='provider', to='multi_table.Place'),
        ),
    ]
