# Generated by Django 2.0.2 on 2018-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_auto_20180209_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='relations',
            field=models.ManyToManyField(through='many_to_many.Relation', to='many_to_many.TwitterUser'),
        ),
    ]
