# Generated by Django 2.0.2 on 2018-02-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkey', '0003_auto_20180205_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='id',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
