# Generated by Django 2.0.2 on 2018-02-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foreignkey', '0004_auto_20180205_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type',
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
