# Generated by Django 2.0.2 on 2018-02-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20180211_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
